namespace Generated.Mapper;

public class AttributeGeneratorHelper
{
    public const string GeneratedCodeAttribute = """[global::System.CodeDom.Compiler.GeneratedCodeAttribute("GeneratedMapper", "1.0.0.0")]""";
    //language=c#
    public const string GeneratedHeaderComment = """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable
        """;
    //language=c#
    public const string MapperAttribute = $$"""
        {{GeneratedHeaderComment}}
        
        namespace Generated.Mapper.Helpers;

        {{GeneratedCodeAttribute}}
        [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
        public class MapperAttribute : global::System.Attribute
        {}
        """;

    //language=c#
    public const string MapAttribute = $$"""
        {{GeneratedHeaderComment}}

        namespace Generated.Mapper.Helpers;

        {{GeneratedCodeAttribute}}
        [global::System.AttributeUsage(global::System.AttributeTargets.Property, AllowMultiple = true)]
        public class MapAttribute<T> : global::System.Attribute
        {}
        """;
}
